### PR TITLE
fix: empty XIC plot if no data (issue #549)

### PR DESCRIPTION
**Pull request by jorainer**
This fixes issue #549: an empty plot is created if no data points are available for a file.

### CODE REVIEW

**Review by lgatto — APPROVED** [review]
Looks good to me, thanks.

**Comment by lgatto** [comment]
@jorainer - this has apparently not been merged?

**Comment by jorainer** [comment]
Ah, no, that's true. Can you please merge and push to BioC (I think I have no access to the MSnbase BioC repo)?

**Comment by lgatto** [comment]
But some checks fail at the moment.

**Comment by jorainer** [comment]
It's a very strange error that I get in the centroiding vignette only when running either `R CMD build MSnbase` or `R CMD check MSnbase`. The error does not happen when rendering the vignette with `rmarkdown` alone.

**Comment by jorainer** [comment]
Forget my previous comment. It was a very stupid error. I called the `splitByFile,MSnExp` method in the wrong way. It was working on `OnDiskMSnExp` objects, but not on `MSnExp` objects. Now it should be fine.

**Comment by lgatto** [comment]
Pushed to Bioc.

**Pull request merged**
