### PR TITLE
Rename Spectra and Chromatograms

### PR DESCRIPTION
**Pull request by jorainer**
- rename `Spectra` to `MSpectra` (issue #514)
- rename `Chromatograms` to `MChromatograms` (issue #515)

### CODE REVIEW

**Comment by jorainer** [comment]
I don't quite understand why travis fails - all running smoothly locally.

**Comment by jorainer** [comment]
OK, warnings fixed.

**Comment by lgatto** [comment]
What about also renaming `Chromatogram` to `MChromatogram`? I know it isn't a matrix, but it would make the relation `Chromatogram` -> `MChromatograms` more explicit and it would also avoid ambiguity with `MSnbase::Chromatogram` and `Spectra::Chromatograms`.

**Comment by jorainer** [comment]
Hm, I don't think that would be necessary. To be consistent we should then also rename `Spectrum`, `Spectrum1`, `Spectrum2` to `MSpectrum`, ...

**Comment by lgatto** [comment]
There is no `Spectrum*` in `Spectra` (and there will never be).

**Comment by jorainer** [comment]
But that's the same with `Chromatogram` - we will not have a `Chromatograms::Chromatogram` class. In general I'm OK with renaming `MSnbase::Chromatogram` to `MSnbase::MChromatogram`, I just wanted to do as little changes as possible, because these class renamings might cause downstream problems in other packages.

**Comment by lgatto** [comment]
It isn't critical at this stage, I just want to avoid having to do another such refactoring another time. 

Regarding the `Spectrum` class, do you remember the discussion that lead to [this](https://github.com/lgatto/Spectrum). If this ever materialises, we might very well hit a clash with `MSnbase`. I thought we would stay on the safe side with anticipating anything, even unlikely, by renaming to `MChromatogram`.

**Comment by lgatto** [comment]
I looked at the changes and am doing some local checks for the current PR. Will merge soon.

**Pull request merged**
