### PR TITLE
refactor: add parameter ppm to combineSpectraMovingWindow

### PR DESCRIPTION
**Pull request by jorainer**
- Add parameter `ppm` to `combineSpectraMovingWindow` (issue #521).

### CODE REVIEW

**Comment by lgatto** [comment]
I assume this needs to be pushed upstreams to `devel`, or is it to `RELEASE_3_10`?

**Comment by jorainer** [comment]
Sorry for the late reply - this should go into the current Bioc devel (i.e. Bioc master branch). The fix for RELEASE_3_10 is in branch RELEASE_3_10

**Comment by lgatto** [comment]
Shouldn't this be `RELEASE_3_11`?

**Comment by lgatto** [comment]
I looks like everything is fine, just a version confusion, but waiting for you to confirm.

**Comment by jorainer** [comment]
I added the fix only for the master branch and also for the *old* RELEASE_3_10 because the user from issue #521 could not install a more recent R/Bioc version. The RELEASE_3_10 fix was for him to test if it was working at all.

**Comment by lgatto** [comment]
But I can't push to `RELEASE_3_10` any more, this is the old Bioconductor release version. If there's a change to backport to release, it must be 3.11.

**Comment by lgatto** [comment]
So there isn't anything to push to any release branch.

**Comment by lgatto** [comment]
If ok for you, I would prefer to delete the `RELEASE_3_*` branches here on github, to avoid any confusion.

**Comment by jorainer** [comment]
Sure, no problem. Deleted the RELEASE_ branch

**Pull request merged**
