### PR TITLE
fix: fix issue in compareChromatograms

### PR DESCRIPTION
**Pull request by jorainer**

### CODE REVIEW

**Comment by jorainer** [comment]
I am somehow unable to run the unit tests locally (unable to download some data files) - can you eventually test it locally on your system if the unit tests fail here @lgatto ?

**Comment by jorainer** [comment]
I keep getting this error (also locally but I thought it's a network problem I have) - can you maybe also look into this @lgatto ? I have no idea how to fix that

```r
── Error (test_MSmap.R:7:1): (code run outside of `test_that()`) ───────────────
Error: Error: failed to load resource
  name: AH49008
  title: PXD000001: raw mass spectrometry data
  reason: 1 resources failed to download
Backtrace:
    █
 1. ├─ah[["AH49008"]] test_MSmap.R:7:0
 2. └─ah[["AH49008"]]
 3.   └─AnnotationHub:::.local(x, i, j = j, ...)
 4.     └─AnnotationHub:::.Hub_get1(x[idx], force = force, verbose = verbose)
 5.       └─base::tryCatch(...)
 6.         └─base:::tryCatchList(expr, classes, parentenv, handlers)
 7.           └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 8.             └─value[[3L]](cond)
```

**Comment by lgatto** [comment]
Yes, running the tests locally - the error is probably related to the change in default cache and/or the recent and ongoing [PRIDE [failure](https://github.com/lgatto/rpx/issues/17).

**Review by lgatto — APPROVED** [review]
I successfully verified all unit tests locally on release and devel.

**Comment by lgatto** [comment]
Pushed to Bioc. If you backport to RELEASE_3_14 here on github, I'll do the same for release.

**Comment by jorainer** [comment]
Thanks @lgatto ! This will then hopefully also fix the dev builds. I will now also make a PR to the RELEASE_3_14 branch with the same fix.

**Pull request merged**
