### PR TITLE
custom function for reading SkyLine output

### PR DESCRIPTION
**Pull request by vladpetyuk**

### CODE REVIEW

**Comment by lgatto** [comment]
@vladpetyuk I would be happy to include the function. Could write add the roxygen documentation and demonstrate the function using a small example file, to be added in `inst/extdata`.

**Comment by lgatto** [comment]
Vlad, any interest in adding this function?

**Comment by vladpetyuk** [comment]
Certainly.  I'll get to it at some point.

**Comment by lgatto** [comment]
No worries, thanks. Release is imminent, so I would suggest to wait anyway.

**Comment by lgatto** [comment]
@vladpetyuk - is this still on your radar?

**Comment by sgibb** [comment]
@vladpetyuk I close this PR after > 3 years of inactivity. If you still interested in having this functionality in `MSnbase` please feel free to reopen it.

**Pull request closed without merging**
