### PR TITLE
Add first set of methods for Spectra

### PR DESCRIPTION
**Pull request by jotsetung**
As predicted by @sgibb, here are the first set of methods implemented for `Spectra`: `clean`, `filterMz`, `pickPeaks`, `removePeaks` and `smooth` for `Spectra` along with related unit tests and documentation.

### CODE REVIEW

**Comment by lgatto** [comment]
@jotsetung - should this PR (and possibly others) be merged before the 3.7 code freeze this afternoon?

**Comment by jotsetung** [comment]
Wow, the code freeze is already this afternoon? Would be nice to have them, yes. I'll address the issues.

**Comment by jotsetung** [comment]
Actually, this should go into Bioc 3.8 not 3.7, so it does not have to be merged today.

**Comment by lgatto** [comment]
Ok - the previous PR is merged and will be available in the next release though.

**Comment by lgatto** [comment]
@jotsetung - do you want me to merge and push to bioc asap asap, or give @sgibb a chance to look at it?

**Comment by jotsetung** [comment]
There is not much of a functionality added in this pull request, so I think it should be save to merge even without @sgibb's excellent code reviews.

**Comment by lgatto** [comment]
Pushed to bioc,

**Pull request merged**
